name: Release

on:
   push:
      branches:
         - main

permissions:
   contents: write

concurrency:
   group: release-${{ github.ref }}
   cancel-in-progress: true

jobs:
   release:
      runs-on: ubuntu-latest
      env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
         - uses: jdx/mise-action@v2
         - run: mise run package
